//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationmain.model.izvestaj;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.tim123.vaccinationmain.model.tipovi.TVakcina;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Period"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Od" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Do" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Broj_podnetih_dokumenata_o_interesovanju" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Broj_primljenih_zahteva_za_digitalni_zeleni_sertifikat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Broj_izdatih_zahteva_za_digitalni_zeleni_sertifikat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Ukupan_broj_datih_doza_vakcine" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Doze"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded"&gt;
 *                   &lt;element name="Doza"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Broj_datih_doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="redni_broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Raspodela_po_proizvodjacima"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded"&gt;
 *                   &lt;element name="Proizvodjac"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Naziv" type="{http://www.xws.org/tipovi}TVakcina"/&gt;
 *                             &lt;element name="Broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumIzdavanja",
    "period",
    "brojPodnetihDokumenataOInteresovanju",
    "brojPrimljenihZahtevaZaDigitalniZeleniSertifikat",
    "brojIzdatihZahtevaZaDigitalniZeleniSertifikat",
    "ukupanBrojDatihDozaVakcine",
    "doze",
    "raspodelaPoProizvodjacima"
})
@XmlRootElement(name = "Izvestaj")
public class Izvestaj {

    @XmlElement(name = "Datum_izdavanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlElement(name = "Period", required = true)
    protected Period period;
    @XmlElement(name = "Broj_podnetih_dokumenata_o_interesovanju", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojPodnetihDokumenataOInteresovanju;
    @XmlElement(name = "Broj_primljenih_zahteva_za_digitalni_zeleni_sertifikat", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojPrimljenihZahtevaZaDigitalniZeleniSertifikat;
    @XmlElement(name = "Broj_izdatih_zahteva_za_digitalni_zeleni_sertifikat", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojIzdatihZahtevaZaDigitalniZeleniSertifikat;
    @XmlElement(name = "Ukupan_broj_datih_doza_vakcine", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ukupanBrojDatihDozaVakcine;
    @XmlElement(name = "Doze", required = true)
    protected Doze doze;
    @XmlElement(name = "Raspodela_po_proizvodjacima", required = true)
    protected RaspodelaPoProizvodjacima raspodelaPoProizvodjacima;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the brojPodnetihDokumenataOInteresovanju property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPodnetihDokumenataOInteresovanju() {
        return brojPodnetihDokumenataOInteresovanju;
    }

    /**
     * Sets the value of the brojPodnetihDokumenataOInteresovanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPodnetihDokumenataOInteresovanju(BigInteger value) {
        this.brojPodnetihDokumenataOInteresovanju = value;
    }

    /**
     * Gets the value of the brojPrimljenihZahtevaZaDigitalniZeleniSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPrimljenihZahtevaZaDigitalniZeleniSertifikat() {
        return brojPrimljenihZahtevaZaDigitalniZeleniSertifikat;
    }

    /**
     * Sets the value of the brojPrimljenihZahtevaZaDigitalniZeleniSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPrimljenihZahtevaZaDigitalniZeleniSertifikat(BigInteger value) {
        this.brojPrimljenihZahtevaZaDigitalniZeleniSertifikat = value;
    }

    /**
     * Gets the value of the brojIzdatihZahtevaZaDigitalniZeleniSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojIzdatihZahtevaZaDigitalniZeleniSertifikat() {
        return brojIzdatihZahtevaZaDigitalniZeleniSertifikat;
    }

    /**
     * Sets the value of the brojIzdatihZahtevaZaDigitalniZeleniSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojIzdatihZahtevaZaDigitalniZeleniSertifikat(BigInteger value) {
        this.brojIzdatihZahtevaZaDigitalniZeleniSertifikat = value;
    }

    /**
     * Gets the value of the ukupanBrojDatihDozaVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUkupanBrojDatihDozaVakcine() {
        return ukupanBrojDatihDozaVakcine;
    }

    /**
     * Sets the value of the ukupanBrojDatihDozaVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUkupanBrojDatihDozaVakcine(BigInteger value) {
        this.ukupanBrojDatihDozaVakcine = value;
    }

    /**
     * Gets the value of the doze property.
     * 
     * @return
     *     possible object is
     *     {@link Doze }
     *     
     */
    public Doze getDoze() {
        return doze;
    }

    /**
     * Sets the value of the doze property.
     * 
     * @param value
     *     allowed object is
     *     {@link Doze }
     *     
     */
    public void setDoze(Doze value) {
        this.doze = value;
    }

    /**
     * Gets the value of the raspodelaPoProizvodjacima property.
     * 
     * @return
     *     possible object is
     *     {@link RaspodelaPoProizvodjacima }
     *     
     */
    public RaspodelaPoProizvodjacima getRaspodelaPoProizvodjacima() {
        return raspodelaPoProizvodjacima;
    }

    /**
     * Sets the value of the raspodelaPoProizvodjacima property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaspodelaPoProizvodjacima }
     *     
     */
    public void setRaspodelaPoProizvodjacima(RaspodelaPoProizvodjacima value) {
        this.raspodelaPoProizvodjacima = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;element name="Doza"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Broj_datih_doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="redni_broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doza"
    })
    public static class Doze {

        @XmlElement(name = "Doza")
        protected List<Doza> doza;

        /**
         * Gets the value of the doza property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doza property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoza().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Doza }
         * 
         * 
         */
        public List<Doza> getDoza() {
            if (doza == null) {
                doza = new ArrayList<Doza>();
            }
            return this.doza;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Broj_datih_doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="redni_broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojDatihDoza"
        })
        public static class Doza {

            @XmlElement(name = "Broj_datih_doza", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger brojDatihDoza;
            @XmlAttribute(name = "redni_broj")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger redniBroj;

            /**
             * Gets the value of the brojDatihDoza property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBrojDatihDoza() {
                return brojDatihDoza;
            }

            /**
             * Sets the value of the brojDatihDoza property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBrojDatihDoza(BigInteger value) {
                this.brojDatihDoza = value;
            }

            /**
             * Gets the value of the redniBroj property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRedniBroj() {
                return redniBroj;
            }

            /**
             * Sets the value of the redniBroj property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRedniBroj(BigInteger value) {
                this.redniBroj = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Od" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Do" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "od",
        "_do"
    })
    public static class Period {

        @XmlElement(name = "Od", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar od;
        @XmlElement(name = "Do", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar _do;

        /**
         * Gets the value of the od property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOd() {
            return od;
        }

        /**
         * Sets the value of the od property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOd(XMLGregorianCalendar value) {
            this.od = value;
        }

        /**
         * Gets the value of the do property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDo() {
            return _do;
        }

        /**
         * Sets the value of the do property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDo(XMLGregorianCalendar value) {
            this._do = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;element name="Proizvodjac"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Naziv" type="{http://www.xws.org/tipovi}TVakcina"/&gt;
     *                   &lt;element name="Broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proizvodjac"
    })
    public static class RaspodelaPoProizvodjacima {

        @XmlElement(name = "Proizvodjac")
        protected List<Proizvodjac> proizvodjac;

        /**
         * Gets the value of the proizvodjac property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the proizvodjac property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProizvodjac().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Proizvodjac }
         * 
         * 
         */
        public List<Proizvodjac> getProizvodjac() {
            if (proizvodjac == null) {
                proizvodjac = new ArrayList<Proizvodjac>();
            }
            return this.proizvodjac;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Naziv" type="{http://www.xws.org/tipovi}TVakcina"/&gt;
         *         &lt;element name="Broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "brojDoza"
        })
        public static class Proizvodjac {

            @XmlElement(name = "Naziv", required = true)
            @XmlSchemaType(name = "string")
            protected TVakcina naziv;
            @XmlElement(name = "Broj_doza", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger brojDoza;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link TVakcina }
             *     
             */
            public TVakcina getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link TVakcina }
             *     
             */
            public void setNaziv(TVakcina value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the brojDoza property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBrojDoza() {
                return brojDoza;
            }

            /**
             * Sets the value of the brojDoza property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBrojDoza(BigInteger value) {
                this.brojDoza = value;
            }

        }

    }

}
