//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationmain.model.saglasnost;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xws.saglasnost package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xws.saglasnost
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TVakcina }
     * 
     */
    public TVakcina createTVakcina() {
        return new TVakcina();
    }

    /**
     * Create an instance of {@link TEvidencija }
     * 
     */
    public TEvidencija createTEvidencija() {
        return new TEvidencija();
    }

    /**
     * Create an instance of {@link TEvidencija.PrivremeneKontraindikacije }
     * 
     */
    public TEvidencija.PrivremeneKontraindikacije createTEvidencijaPrivremeneKontraindikacije() {
        return new TEvidencija.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link TPacijent }
     * 
     */
    public TPacijent createTPacijent() {
        return new TPacijent();
    }

    /**
     * Create an instance of {@link TPacijent.KorisnikUstanoveSocijalneZasttite }
     * 
     */
    public TPacijent.KorisnikUstanoveSocijalneZasttite createTPacijentKorisnikUstanoveSocijalneZasttite() {
        return new TPacijent.KorisnikUstanoveSocijalneZasttite();
    }

    /**
     * Create an instance of {@link TPacijent.RadniStatus }
     * 
     */
    public TPacijent.RadniStatus createTPacijentRadniStatus() {
        return new TPacijent.RadniStatus();
    }

    /**
     * Create an instance of {@link Saglasnost }
     * 
     */
    public com.tim123.vaccinationmain.model.saglasnost.Saglasnost createSaglasnost() {
        return new com.tim123.vaccinationmain.model.saglasnost.Saglasnost();
    }

    /**
     * Create an instance of {@link TDrzavljanstvo }
     * 
     */
    public TDrzavljanstvo createTDrzavljanstvo() {
        return new TDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TVakcina.Ekstremitet }
     * 
     */
    public TVakcina.Ekstremitet createTVakcinaEkstremitet() {
        return new TVakcina.Ekstremitet();
    }

    /**
     * Create an instance of {@link TEvidencija.Lekar }
     * 
     */
    public TEvidencija.Lekar createTEvidencijaLekar() {
        return new TEvidencija.Lekar();
    }

    /**
     * Create an instance of {@link TEvidencija.Vakcine }
     * 
     */
    public TEvidencija.Vakcine createTEvidencijaVakcine() {
        return new TEvidencija.Vakcine();
    }

    /**
     * Create an instance of {@link TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija }
     * 
     */
    public TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija createTEvidencijaPrivremeneKontraindikacijePrivremenaKontraindikacija() {
        return new TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija();
    }

    /**
     * Create an instance of {@link TPacijent.Saglasnost }
     * 
     */
    public TPacijent.Saglasnost createTPacijentSaglasnost() {
        return new TPacijent.Saglasnost();
    }

    /**
     * Create an instance of {@link TPacijent.KorisnikUstanoveSocijalneZasttite.Sediste }
     * 
     */
    public TPacijent.KorisnikUstanoveSocijalneZasttite.Sediste createTPacijentKorisnikUstanoveSocijalneZasttiteSediste() {
        return new TPacijent.KorisnikUstanoveSocijalneZasttite.Sediste();
    }

    /**
     * Create an instance of {@link TPacijent.RadniStatus.Zaposlen }
     * 
     */
    public TPacijent.RadniStatus.Zaposlen createTPacijentRadniStatusZaposlen() {
        return new TPacijent.RadniStatus.Zaposlen();
    }

}
