//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationmain.model.saglasnost;

import com.tim123.vaccinationmain.model.tipovi.TCBrojPasosa;
import com.tim123.vaccinationmain.model.tipovi.TCEBS;
import com.tim123.vaccinationmain.model.tipovi.TCJMBG;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDrzavljanstvo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDrzavljanstvo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="JMBG" type="{http://www.xws.org/tipovi}TCJMBG"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Naziv_stranog_drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;choice&gt;
 *             &lt;element name="Broj_pasosa" type="{http://www.xws.org/tipovi}TCBrojPasosa"/&gt;
 *             &lt;element name="EBS" type="{http://www.xws.org/tipovi}TCEBS"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDrzavljanstvo", propOrder = {
    "jmbg",
    "nazivStranogDrzavljanstva",
    "brojPasosa",
    "ebs"
})
public class TDrzavljanstvo {

    @XmlElement(name = "JMBG")
    protected TCJMBG jmbg;
    @XmlElement(name = "Naziv_stranog_drzavljanstva")
    protected String nazivStranogDrzavljanstva;
    @XmlElement(name = "Broj_pasosa")
    protected TCBrojPasosa brojPasosa;
    @XmlElement(name = "EBS")
    protected TCEBS ebs;

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link TCJMBG }
     *     
     */
    public TCJMBG getJMBG() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCJMBG }
     *     
     */
    public void setJMBG(TCJMBG value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the nazivStranogDrzavljanstva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivStranogDrzavljanstva() {
        return nazivStranogDrzavljanstva;
    }

    /**
     * Sets the value of the nazivStranogDrzavljanstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivStranogDrzavljanstva(String value) {
        this.nazivStranogDrzavljanstva = value;
    }

    /**
     * Gets the value of the brojPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link TCBrojPasosa }
     *     
     */
    public TCBrojPasosa getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCBrojPasosa }
     *     
     */
    public void setBrojPasosa(TCBrojPasosa value) {
        this.brojPasosa = value;
    }

    /**
     * Gets the value of the ebs property.
     * 
     * @return
     *     possible object is
     *     {@link TCEBS }
     *     
     */
    public TCEBS getEBS() {
        return ebs;
    }

    /**
     * Sets the value of the ebs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCEBS }
     *     
     */
    public void setEBS(TCEBS value) {
        this.ebs = value;
    }

}
