//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:24:56 PM CET 
//


package com.tim123.vaccinationmain.model.saglasnost;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TEvidencija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEvidencija"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Lekar"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Broj_telefona"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="\+?[0-9]+"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Vakcine"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Vakcina" type="{http://www.xws.org/saglasnost}TVakcina" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Privremene_kontraindikacije"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Privremena_kontraindikacija" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Trajne_kontraindikacije" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEvidencija", propOrder = {
    "zdravstvenaUstanova",
    "vakcinacijskiPunkt",
    "lekar",
    "vakcine",
    "privremeneKontraindikacije",
    "trajneKontraindikacije"
})
public class TEvidencija {

    @XmlElement(name = "Zdravstvena_ustanova", required = true)
    protected String zdravstvenaUstanova;
    @XmlElement(name = "Vakcinacijski_punkt", required = true)
    protected String vakcinacijskiPunkt;
    @XmlElement(name = "Lekar", required = true)
    protected TEvidencija.Lekar lekar;
    @XmlElement(name = "Vakcine", required = true)
    protected TEvidencija.Vakcine vakcine;
    @XmlElement(name = "Privremene_kontraindikacije", required = true)
    protected TEvidencija.PrivremeneKontraindikacije privremeneKontraindikacije;
    @XmlElement(name = "Trajne_kontraindikacije")
    protected Object trajneKontraindikacije;

    /**
     * Gets the value of the zdravstvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZdravstvenaUstanova() {
        return zdravstvenaUstanova;
    }

    /**
     * Sets the value of the zdravstvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZdravstvenaUstanova(String value) {
        this.zdravstvenaUstanova = value;
    }

    /**
     * Gets the value of the vakcinacijskiPunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVakcinacijskiPunkt() {
        return vakcinacijskiPunkt;
    }

    /**
     * Sets the value of the vakcinacijskiPunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVakcinacijskiPunkt(String value) {
        this.vakcinacijskiPunkt = value;
    }

    /**
     * Gets the value of the lekar property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencija.Lekar }
     *     
     */
    public TEvidencija.Lekar getLekar() {
        return lekar;
    }

    /**
     * Sets the value of the lekar property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencija.Lekar }
     *     
     */
    public void setLekar(TEvidencija.Lekar value) {
        this.lekar = value;
    }

    /**
     * Gets the value of the vakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencija.Vakcine }
     *     
     */
    public TEvidencija.Vakcine getVakcine() {
        return vakcine;
    }

    /**
     * Sets the value of the vakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencija.Vakcine }
     *     
     */
    public void setVakcine(TEvidencija.Vakcine value) {
        this.vakcine = value;
    }

    /**
     * Gets the value of the privremeneKontraindikacije property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencija.PrivremeneKontraindikacije }
     *     
     */
    public TEvidencija.PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
        return privremeneKontraindikacije;
    }

    /**
     * Sets the value of the privremeneKontraindikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencija.PrivremeneKontraindikacije }
     *     
     */
    public void setPrivremeneKontraindikacije(TEvidencija.PrivremeneKontraindikacije value) {
        this.privremeneKontraindikacije = value;
    }

    /**
     * Gets the value of the trajneKontraindikacije property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTrajneKontraindikacije() {
        return trajneKontraindikacije;
    }

    /**
     * Sets the value of the trajneKontraindikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTrajneKontraindikacije(Object value) {
        this.trajneKontraindikacije = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Broj_telefona"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="\+?[0-9]+"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "brojTelefona"
    })
    public static class Lekar {

        @XmlElement(name = "Ime", required = true)
        protected String ime;
        @XmlElement(name = "Prezime", required = true)
        protected String prezime;
        @XmlElement(name = "Broj_telefona", required = true)
        protected String brojTelefona;

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the brojTelefona property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojTelefona() {
            return brojTelefona;
        }

        /**
         * Sets the value of the brojTelefona property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojTelefona(String value) {
            this.brojTelefona = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Privremena_kontraindikacija" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "privremenaKontraindikacija"
    })
    public static class PrivremeneKontraindikacije {

        @XmlElement(name = "Privremena_kontraindikacija")
        protected List<TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija> privremenaKontraindikacija;

        /**
         * Gets the value of the privremenaKontraindikacija property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the privremenaKontraindikacija property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrivremenaKontraindikacija().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija }
         * 
         * 
         */
        public List<TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija> getPrivremenaKontraindikacija() {
            if (privremenaKontraindikacija == null) {
                privremenaKontraindikacija = new ArrayList<TEvidencija.PrivremeneKontraindikacije.PrivremenaKontraindikacija>();
            }
            return this.privremenaKontraindikacija;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="Dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datumUtvrdjivanja",
            "dijagnoza"
        })
        public static class PrivremenaKontraindikacija {

            @XmlElement(name = "Datum_utvrdjivanja", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumUtvrdjivanja;
            @XmlElement(name = "Dijagnoza", required = true)
            protected String dijagnoza;

            /**
             * Gets the value of the datumUtvrdjivanja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumUtvrdjivanja() {
                return datumUtvrdjivanja;
            }

            /**
             * Sets the value of the datumUtvrdjivanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumUtvrdjivanja(XMLGregorianCalendar value) {
                this.datumUtvrdjivanja = value;
            }

            /**
             * Gets the value of the dijagnoza property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDijagnoza() {
                return dijagnoza;
            }

            /**
             * Sets the value of the dijagnoza property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDijagnoza(String value) {
                this.dijagnoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Vakcina" type="{http://www.xws.org/saglasnost}TVakcina" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vakcina"
    })
    public static class Vakcine {

        @XmlElement(name = "Vakcina")
        protected List<TVakcina> vakcina;

        /**
         * Gets the value of the vakcina property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcina property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcina().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TVakcina }
         * 
         * 
         */
        public List<TVakcina> getVakcina() {
            if (vakcina == null) {
                vakcina = new ArrayList<TVakcina>();
            }
            return this.vakcina;
        }

    }

}
