//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationmain.model.sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xws.sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xws.sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sertifikat }
     * 
     */
    public Sertifikat createSertifikat() {
        return new Sertifikat();
    }

    /**
     * Create an instance of {@link Sertifikat.DatumVreme }
     * 
     */
    public Sertifikat.DatumVreme createSertifikatDatumVreme() {
        return new Sertifikat.DatumVreme();
    }

    /**
     * Create an instance of {@link TVakcinacija }
     * 
     */
    public TVakcinacija createTVakcinacija() {
        return new TVakcinacija();
    }

    /**
     * Create an instance of {@link TTestovi }
     * 
     */
    public TTestovi createTTestovi() {
        return new TTestovi();
    }

    /**
     * Create an instance of {@link TDoza }
     * 
     */
    public TDoza createTDoza() {
        return new TDoza();
    }

    /**
     * Create an instance of {@link TTest }
     * 
     */
    public TTest createTTest() {
        return new TTest();
    }

}
