//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:24:56 PM CET 
//


package com.tim123.vaccinationmain.model.sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tip_testa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Datum_vreme_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Datum_vreme_izdavanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Rezultat" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTest", propOrder = {
    "tipTesta",
    "vrstaUzorka",
    "proizvodjac",
    "datumVremeUzorkovanja",
    "datumVremeIzdavanja",
    "rezultat",
    "laboratorija"
})
public class TTest {

    @XmlElement(name = "Tip_testa", required = true)
    protected String tipTesta;
    @XmlElement(name = "Vrsta_uzorka", required = true)
    protected String vrstaUzorka;
    @XmlElement(name = "Proizvodjac", required = true)
    protected String proizvodjac;
    @XmlElement(name = "Datum_vreme_uzorkovanja", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVremeUzorkovanja;
    @XmlElement(name = "Datum_vreme_izdavanja", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVremeIzdavanja;
    @XmlElement(name = "Rezultat")
    protected boolean rezultat;
    @XmlElement(name = "Laboratorija", required = true)
    protected String laboratorija;

    /**
     * Gets the value of the tipTesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipTesta() {
        return tipTesta;
    }

    /**
     * Sets the value of the tipTesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipTesta(String value) {
        this.tipTesta = value;
    }

    /**
     * Gets the value of the vrstaUzorka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaUzorka() {
        return vrstaUzorka;
    }

    /**
     * Sets the value of the vrstaUzorka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaUzorka(String value) {
        this.vrstaUzorka = value;
    }

    /**
     * Gets the value of the proizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProizvodjac() {
        return proizvodjac;
    }

    /**
     * Sets the value of the proizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProizvodjac(String value) {
        this.proizvodjac = value;
    }

    /**
     * Gets the value of the datumVremeUzorkovanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVremeUzorkovanja() {
        return datumVremeUzorkovanja;
    }

    /**
     * Sets the value of the datumVremeUzorkovanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVremeUzorkovanja(XMLGregorianCalendar value) {
        this.datumVremeUzorkovanja = value;
    }

    /**
     * Gets the value of the datumVremeIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVremeIzdavanja() {
        return datumVremeIzdavanja;
    }

    /**
     * Sets the value of the datumVremeIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVremeIzdavanja(XMLGregorianCalendar value) {
        this.datumVremeIzdavanja = value;
    }

    /**
     * Gets the value of the rezultat property.
     * 
     */
    public boolean isRezultat() {
        return rezultat;
    }

    /**
     * Sets the value of the rezultat property.
     * 
     */
    public void setRezultat(boolean value) {
        this.rezultat = value;
    }

    /**
     * Gets the value of the laboratorija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaboratorija() {
        return laboratorija;
    }

    /**
     * Sets the value of the laboratorija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaboratorija(String value) {
        this.laboratorija = value;
    }

}
