//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:24:56 PM CET 
//


package com.tim123.vaccinationmain.model.tipovi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xws.tipovi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xws.tipovi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TZainteresovanoLice }
     * 
     */
    public TZainteresovanoLice createTZainteresovanoLice() {
        return new TZainteresovanoLice();
    }

    /**
     * Create an instance of {@link TVakcinisanoLice }
     * 
     */
    public TVakcinisanoLice createTVakcinisanoLice() {
        return new TVakcinisanoLice();
    }

    /**
     * Create an instance of {@link TPrimalacPotvrde }
     * 
     */
    public TPrimalacPotvrde createTPrimalacPotvrde() {
        return new TPrimalacPotvrde();
    }

    /**
     * Create an instance of {@link TKontakt }
     * 
     */
    public TKontakt createTKontakt() {
        return new TKontakt();
    }

}
