//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationportal.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.tim123.vaccinationportal.model.tipovi.TDatumKreiranja;
import com.tim123.vaccinationportal.model.tipovi.TVakcinisanoLice;
import com.tim123.vaccinationportal.model.tipovi.TDatumKreiranja;
import com.tim123.vaccinationportal.model.tipovi.TVakcinisanoLice;
import org.apache.xpath.operations.Bool;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Datum" type="{http://www.xws.org/tipovi}TDatumKreiranja"/&gt;
 *         &lt;element name="Podnosilac" type="{http://www.xws.org/tipovi}TVakcinisanoLice"/&gt;
 *         &lt;element name="Razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datum",
    "podnosilac",
    "razlog",
    "mesto"
})
@XmlRootElement(name = "Zahtev")
public class Zahtev {

    @XmlElement(name = "Datum", required = true)
    protected TDatumKreiranja datum;
    @XmlElement(name = "Podnosilac", required = true)
    protected TVakcinisanoLice podnosilac;
    @XmlElement(name = "Razlog", required = true)
    protected String razlog;
    @XmlElement(name = "Mesto", required = true)
    protected String mesto;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "about", required = true)
    protected String about;
    @XmlAttribute(name = "obradjen", required = true)
    protected Boolean obradjen = false;
    @XmlAttribute(name = "xmlns:pred")
    protected String pred = "http://www.xws.org/vacc/#";

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link TDatumKreiranja }
     *     
     */
    public TDatumKreiranja getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatumKreiranja }
     *     
     */
    public void setDatum(TDatumKreiranja value) {
        this.datum = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TVakcinisanoLice }
     *     
     */
    public TVakcinisanoLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVakcinisanoLice }
     *     
     */
    public void setPodnosilac(TVakcinisanoLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the razlog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlog() {
        return razlog;
    }

    /**
     * Sets the value of the razlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlog(String value) {
        this.razlog = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the obradjen property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isObradjen() {
        return obradjen;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObradjen(Boolean value) {
        this.obradjen = value;
    }
}
