//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:24:56 PM CET 
//


package com.tim123.vaccinationmain.model.interesovanje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xws.interesovanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InteresovanjeZeljenaVakcinaPfizerBioNTech_QNAME = new QName("http://www.xws.org/interesovanje", "Pfizer-BioNTech");
    private final static QName _InteresovanjeZeljenaVakcinaSputnikV_QNAME = new QName("http://www.xws.org/interesovanje", "Sputnik_V");
    private final static QName _InteresovanjeZeljenaVakcinaSinopharm_QNAME = new QName("http://www.xws.org/interesovanje", "Sinopharm");
    private final static QName _InteresovanjeZeljenaVakcinaAstraZeneca_QNAME = new QName("http://www.xws.org/interesovanje", "AstraZeneca");
    private final static QName _InteresovanjeZeljenaVakcinaModerna_QNAME = new QName("http://www.xws.org/interesovanje", "Moderna");
    private final static QName _InteresovanjeZeljenaVakcinaBiloKoja_QNAME = new QName("http://www.xws.org/interesovanje", "Bilo_koja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xws.interesovanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Interesovanje }
     * 
     */
    public Interesovanje createInteresovanje() {
        return new Interesovanje();
    }

    /**
     * Create an instance of {@link Interesovanje.Drzavljanstvo }
     * 
     */
    public Interesovanje.Drzavljanstvo createInteresovanjeDrzavljanstvo() {
        return new Interesovanje.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina }
     * 
     */
    public Interesovanje.ZeljenaVakcina createInteresovanjeZeljenaVakcina() {
        return new Interesovanje.ZeljenaVakcina();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "Pfizer-BioNTech", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaPfizerBioNTech(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaPfizerBioNTech_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "Sputnik_V", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaSputnikV(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaSputnikV_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "Sinopharm", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaSinopharm(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaSinopharm_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "AstraZeneca", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaAstraZeneca(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaAstraZeneca_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "Moderna", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaModerna(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaModerna_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xws.org/interesovanje", name = "Bilo_koja", scope = Interesovanje.ZeljenaVakcina.class)
    public JAXBElement<Object> createInteresovanjeZeljenaVakcinaBiloKoja(Object value) {
        return new JAXBElement<Object>(_InteresovanjeZeljenaVakcinaBiloKoja_QNAME, Object.class, Interesovanje.ZeljenaVakcina.class, value);
    }

}
