//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationportal.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TVakcina complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TVakcina"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Datum_davanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Ekstremitet"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="DR" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="LR" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVakcina", propOrder = {
    "naziv",
    "datumDavanja",
    "nacinDavanja",
    "ekstremitet",
    "serija",
    "proizvodjac",
    "nezeljenaReakcija"
})
public class TVakcina {

    @XmlElement(name = "Naziv", required = true)
    protected String naziv;
    @XmlElement(name = "Datum_davanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDavanja;
    @XmlElement(name = "Nacin_davanja", required = true)
    protected String nacinDavanja;
    @XmlElement(name = "Ekstremitet", required = true)
    protected Ekstremitet ekstremitet;
    @XmlElement(name = "Serija", required = true)
    protected String serija;
    @XmlElement(name = "Proizvodjac", required = true)
    protected String proizvodjac;
    @XmlElement(name = "Nezeljena_reakcija", required = true)
    protected String nezeljenaReakcija;

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the datumDavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDavanja() {
        return datumDavanja;
    }

    /**
     * Sets the value of the datumDavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDavanja(XMLGregorianCalendar value) {
        this.datumDavanja = value;
    }

    /**
     * Gets the value of the nacinDavanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinDavanja() {
        return nacinDavanja;
    }

    /**
     * Sets the value of the nacinDavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinDavanja(String value) {
        this.nacinDavanja = value;
    }

    /**
     * Gets the value of the ekstremitet property.
     * 
     * @return
     *     possible object is
     *     {@link Ekstremitet }
     *     
     */
    public Ekstremitet getEkstremitet() {
        return ekstremitet;
    }

    /**
     * Sets the value of the ekstremitet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ekstremitet }
     *     
     */
    public void setEkstremitet(Ekstremitet value) {
        this.ekstremitet = value;
    }

    /**
     * Gets the value of the serija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerija() {
        return serija;
    }

    /**
     * Sets the value of the serija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerija(String value) {
        this.serija = value;
    }

    /**
     * Gets the value of the proizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProizvodjac() {
        return proizvodjac;
    }

    /**
     * Sets the value of the proizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProizvodjac(String value) {
        this.proizvodjac = value;
    }

    /**
     * Gets the value of the nezeljenaReakcija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNezeljenaReakcija() {
        return nezeljenaReakcija;
    }

    /**
     * Sets the value of the nezeljenaReakcija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNezeljenaReakcija(String value) {
        this.nezeljenaReakcija = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="DR" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="LR" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dr",
        "lr"
    })
    public static class Ekstremitet {

        @XmlElement(name = "DR")
        protected Object dr;
        @XmlElement(name = "LR")
        protected Object lr;


        /**
         * Gets the value of the dr property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDR() {
            return dr;
        }

        /**
         * Sets the value of the dr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDR(Object value) {
            this.dr = value;
        }

        /**
         * Gets the value of the lr property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLR() {
            return lr;
        }

        /**
         * Sets the value of the lr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLR(Object value) {
            this.lr = value;
        }

    }

}
