//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//


package com.tim123.vaccinationportal.model.interesovanje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xws.interesovanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xws.interesovanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Interesovanje }
     * 
     */
    public Interesovanje createInteresovanje() {
        return new Interesovanje();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina }
     * 
     */
    public Interesovanje.ZeljenaVakcina createInteresovanjeZeljenaVakcina() {
        return new Interesovanje.ZeljenaVakcina();
    }

    /**
     * Create an instance of {@link Interesovanje.Drzavljanstvo }
     * 
     */
    public Interesovanje.Drzavljanstvo createInteresovanjeDrzavljanstvo() {
        return new Interesovanje.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Interesovanje.DobrovoljniDavalacKrvi }
     * 
     */
    public Interesovanje.DobrovoljniDavalacKrvi createInteresovanjeDobrovoljniDavalacKrvi() {
        return new Interesovanje.DobrovoljniDavalacKrvi();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.PfizerBioNTech }
     * 
     */
    public Interesovanje.ZeljenaVakcina.PfizerBioNTech createInteresovanjeZeljenaVakcinaPfizerBioNTech() {
        return new Interesovanje.ZeljenaVakcina.PfizerBioNTech();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.SputnikV }
     * 
     */
    public Interesovanje.ZeljenaVakcina.SputnikV createInteresovanjeZeljenaVakcinaSputnikV() {
        return new Interesovanje.ZeljenaVakcina.SputnikV();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.Sinopharm }
     * 
     */
    public Interesovanje.ZeljenaVakcina.Sinopharm createInteresovanjeZeljenaVakcinaSinopharm() {
        return new Interesovanje.ZeljenaVakcina.Sinopharm();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.AstraZeneca }
     * 
     */
    public Interesovanje.ZeljenaVakcina.AstraZeneca createInteresovanjeZeljenaVakcinaAstraZeneca() {
        return new Interesovanje.ZeljenaVakcina.AstraZeneca();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.Moderna }
     * 
     */
    public Interesovanje.ZeljenaVakcina.Moderna createInteresovanjeZeljenaVakcinaModerna() {
        return new Interesovanje.ZeljenaVakcina.Moderna();
    }

    /**
     * Create an instance of {@link Interesovanje.ZeljenaVakcina.BiloKoja }
     * 
     */
    public Interesovanje.ZeljenaVakcina.BiloKoja createInteresovanjeZeljenaVakcinaBiloKoja() {
        return new Interesovanje.ZeljenaVakcina.BiloKoja();
    }

    /**
     * Create an instance of {@link Interesovanje.Drzavljanstvo.DrzavljaninRepublikeSrbije }
     * 
     */
    public Interesovanje.Drzavljanstvo.DrzavljaninRepublikeSrbije createInteresovanjeDrzavljanstvoDrzavljaninRepublikeSrbije() {
        return new Interesovanje.Drzavljanstvo.DrzavljaninRepublikeSrbije();
    }

    /**
     * Create an instance of {@link Interesovanje.Drzavljanstvo.StraniDrzavljaninSaBoravkomURS }
     * 
     */
    public Interesovanje.Drzavljanstvo.StraniDrzavljaninSaBoravkomURS createInteresovanjeDrzavljanstvoStraniDrzavljaninSaBoravkomURS() {
        return new Interesovanje.Drzavljanstvo.StraniDrzavljaninSaBoravkomURS();
    }

    /**
     * Create an instance of {@link Interesovanje.Drzavljanstvo.StraniDrzavljaninBezBoravkaURS }
     * 
     */
    public Interesovanje.Drzavljanstvo.StraniDrzavljaninBezBoravkaURS createInteresovanjeDrzavljanstvoStraniDrzavljaninBezBoravkaURS() {
        return new Interesovanje.Drzavljanstvo.StraniDrzavljaninBezBoravkaURS();
    }

}
