//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 06:34:26 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xws.org/interesovanje",
        xmlns = {
                @XmlNs(namespaceURI = "http://www.xws.org/vacc/#", prefix = "pred"),
                @XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema#", prefix = "xs"),
                @XmlNs(namespaceURI = "http://www.xws.org/tipovi", prefix = "tip")
        },
        elementFormDefault = XmlNsForm.QUALIFIED)
package com.tim123.vaccinationportal.model.interesovanje;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;